### ISSUE TITLE
Crash while processing a file

### ISSUE THREAD

**Issue by harelba** [cube2222/octosql#132]
Hi, when processing the following, octosql fails on a "couldn't get record stream for execution" error.

Here's a reproduction of the issue. The reason for the `cut` operation is because I've tried bysecting in order to find in which cases the issue happens. The command below fails. When changing the 13 to 12, it works. Any value above 12 would crash the program.

```
cat baseline-data.csv | cut -d ',' -f 1-13 > actual-data.csv ; octosql -c example-config.octosql "select count(*) from bmdata x"
```

The matching config file (`./example-config.octosql`) is this:
```
dataSources:
  - name: bmdata
    type: csv
    config:
      path: "actual-data.csv"
```

The reason i've suspected the column count is kind of incidental. I'm the writer of a command-line sql querying tool called q (http://harelba.github.io/q/) and I'm doing some benchmarks on it and similar tools. The benchmark runs on files with different column counts. All the octosql runs above 12 columns fail the same way, so I've suspected some limit on the column count. Obviously, this might not be the root cause for the failures.

I'd be glad to provide more information or answer more questions if needed.

For some reason github doesn't allow me to do an upload. I'll try to send it in the next comment.

Harel

**Comment by harelba** [comment]
[reproduction-data.tar.gz](https://github.com/cube2222/octosql/files/3463573/reproduction-data.tar.gz)

**Comment by cube2222** [comment]
Hey Harel,
Thanks really much for the issue!

It crashes because currently, OctoSQL requires csv files to have a header row (good idea to fix this). Which means it uses the first row for the column names.

The second and 12th column both have values SACRAMENTO, but column names need to be unique.

I've checked it out and the error should say that (and it does for me):
"couldn't run plan: couldn't get record stream from execution plan: couldn't get data RecordStream: column names not unique"

I've created an issue to support for no header row: https://github.com/cube2222/octosql/issues/133

Thanks again!

**Comment by cube2222** [comment]
Closing this. Reopen whenever you want.

**Comment by harelba** [comment]
Sorry for the late reply, thanks for checking this out. This is indeed the case, I saw that it doesn't detect the headers, but thought that the purposes of the benchmark it's not that important, but clearly it is :)

Thanks! I'll send the benchmark info when ready.

**Comment by cube2222** [comment]
I'd really appreciate that! (though we'll probably end up last for now 😉)
